name: tests

on:
  push:

jobs:
  tests:
    strategy:
      fail-fast: false # Let the workflow continue as much as possible
      matrix:
        include:
          # - os: ubuntu-latest
          #   lisp: sbcl-bin
          # - os: macos-latest
          #   lisp: sbcl-bin
          - os: windows-latest
            lisp: sbcl-bin
    defaults:
      run:
        shell: lispsh {0}
    env:
      LISP: ${{ matrix.lisp }}
    name: test with ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: 40ants/setup-lisp@v3
      - run: ros config
      - run: which ros
